-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 30, 2014 at 09:02 AM
-- Server version: 5.6.20
-- PHP Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `cs174`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE IF NOT EXISTS `fun_video` (
`id` int(11) NOT NULL,
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=217 ;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(0, 'Korean Taekwondo Video', 'http://www.youtube.com/watch?v=rEhkwwLh7_g', 11, '480', 'A taekwondo video from an international tournament hope u guys like it', 'English', 9002323, 'Entertainment,Application,Group demo,Others', 'http://i.ytimg.com/vi/rEhkwwLh7_g/mqdefault.jpg', 'taekwondo'),
(1, 'Taekwondo WTF Highlight Madrid 2005', 'https://www.youtube.com/watch?v=OpNzysRPL4A', 4, '240', 'Highlight zrobiony przeze mnie z materialow z Eurosportu! muzyka: Benny Benassi ft.Dhany - Hit My Heart GET READY FOR THE ...', 'English', 285696, 'Entertainment', 'http://i.ytimg.com/vi/OpNzysRPL4A/mqdefault.jpg', 'taekwondo'),
(2, 'Jeet Kune do vs Tae Kwon Do Ninjutsu', 'http://www.youtube.com/watch?v=_S_TYxAwXnE', 6, '480', 'Filmed and edit by Narayana Cabral.', 'English', 236441, 'Entertainment', 'http://i.ytimg.com/vi/_S_TYxAwXnE/mqdefault.jpg', 'taekwondo, dance'),
(3, 'Tae Kwon Do - Axe Kick', 'http://www.youtube.com/watch?v=_xZVhlmpUXY', 1, '240', 'Use this move when your opponent is on the ground.', 'English', 595730, 'Tutorial', 'http://i.ytimg.com/vi/_xZVhlmpUXY/mqdefault.jpg', 'taekwondo'),
(4, 'Revolution Of Kicking Vol 1 (Side Kick)', 'http://www.youtube.com/watch?v=-AQTmu7ULck', 6, '360', 'Please Subscribe to my videos to see more action!=- High Quality videos from Mooto. This video is a complete tutorial of the ...', 'Non-English', 64249, 'Tutorial', 'http://i.ytimg.com/vi/-AQTmu7ULck/mqdefault.jpg', 'taekwondo'),
(5, 'Korean National Taekwondo Demo Team', 'http://www.youtube.com/watch?v=-IUEwXoCXFE', 5, '240', 'Korean National Taekwondo Demo Team', 'English', 797236, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/-IUEwXoCXFE/mqdefault.jpg', 'taekwondo'),
(6, 'Taekwondo Kickboxing Tutorials Promo (Kwonkicker)', 'http://www.youtube.com/watch?v=0As_JaUVLG8', 11, '480', 'This video features clips from Kwonkicker''s "Taekwondo Kickboxing" tutorials at http://www.youtube.com/kwonkicker . Over 8 ...', 'English', 166152, 'Tutorial', 'http://i.ytimg.com/vi/0As_JaUVLG8/mqdefault.jpg', 'taekwondo'),
(7, 'Taekwondo Back Kick vs Side Step Counter (taekwonw', 'http://www.youtube.com/watch?v=0id9X4IRBQI', 2, '480', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 59631, 'Tutorial', 'http://i.ytimg.com/vi/0id9X4IRBQI/mqdefault.jpg', 'taekwondo, back kick'),
(8, 'WTF Taekwondo - Poomsae Koryo - Korean World Champ', 'http://www.youtube.com/watch?v=0Z_4r-wssy0', 1, '480', '', 'Non-English', 97593, 'Tutorial', 'http://i.ytimg.com/vi_webp/0Z_4r-wssy0/mqdefault.webp', 'taekwondo'),
(9, 'South Korean Special Forces - Taekwondo WTF demons', 'http://www.youtube.com/watch?v=15NSM5yEt2M', 10, '360', 'South Korean Special Forces - Taekwondo WTF demonstration.', 'Non-English', 1130432, 'Tutorial', 'http://i.ytimg.com/vi_webp/15NSM5yEt2M/mqdefault.webp', 'taekwondo'),
(10, 'How to Kick Faster - Combining Muay Thai & Taekwon', 'http://www.youtube.com/watch?v=1fMK6AgJPWc', 5, '360', 'Here is the first video of a new fightTIPS series: Trainer''s Tip (New upload every Sunday). Here, we talk about improving kick ...', 'English', 88665, 'Tutorial', 'http://i.ytimg.com/vi_webp/1fMK6AgJPWc/mqdefault.webp', 'taekwondo, kick'),
(11, 'Taekwondo Action Movie (Real Contact Hits, 2008)', 'http://www.youtube.com/watch?v=1gdhq_7vPiA', 13, '1080', 'This is the original version of our first official short film, "Johnny Owes", which was produced back in 2008. The version uploaded ... HD', 'English', 217619, 'Entertainment', 'http://i.ytimg.com/vi/1gdhq_7vPiA/mqdefault.jpg', 'taekwondo, movie'),
(12, 'Taekwondo Jump Spin Back kick Tutorial', 'http://www.youtube.com/watch?v=1Hb-1Uyeh1Q', 11, '1080', '"How to Jump Spin Back Kick Tutorial" Taekwondo Kickboxing "Jump Spin Back Kick" (Twigi Bandae Dwit Chagi) tutorial broken ...', 'English', 140797, 'Tutorial', 'http://i.ytimg.com/vi/1Hb-1Uyeh1Q/mqdefault.jpg', 'taekwondo, back kick, jump spin back kick'),
(13, 'Taekwon-do ITF Self Defense Session part 2', 'http://www.youtube.com/watch?v=1iNpsGzVlGQ', 6, '480', 'Master V.Alexandris, 8th Degree ITF E-Mail : master_alexandris@yahoo.gr', 'Non-English', 165545, 'Group demo', 'http://i.ytimg.com/vi_webp/1iNpsGzVlGQ/mqdefault.webp', 'taekwondo'),
(14, 'TAEKWONDO POWER TRAINING WITH BOB', 'http://www.youtube.com/watch?v=1vLMMXW53QQ', 3, '480', 'ENTRAINEMENT AVEC BOB NOTRE GRAND POTE CEST CA LES JOURS FERIES ', 'English', 2625154, 'Tutorial', 'http://i.ytimg.com/vi/1vLMMXW53QQ/mqdefault.jpg', 'taekwondo'),
(15, 'Taekwondo Spinning Hook Kick Tutorial', 'http://www.youtube.com/watch?v=1vqL6DDM8ec', 11, '720', '"How to Spinning Hook Kick Tutorial" Taekwondo Kickboxing "Spinning Hook Kick" tutorial broken down and explained by me ...', 'English', 89420, 'Tutorial', 'http://i.ytimg.com/vi/1vqL6DDM8ec/mqdefault.jpg', 'taekwondo,hook kick, spin hook kick'),
(16, 'Milica Mandic (SRB) Wins Women''s Taekwondo +67kg G', 'http://www.youtube.com/watch?v=1x94IHwuNfA', 13, '1080', 'Serbia''s Milica Mandic defeats France''s Anne-Caroline Graffe to win the gold medal in the women''s taekwondo +67 event in the ...', 'English', 91656, 'Others', 'http://i.ytimg.com/vi/1x94IHwuNfA/mqdefault.jpg', 'taekwondo'),
(17, 'Taekwondo Kicking Tutorials Promo (Ginger Ninja Tr', 'http://www.youtube.com/watch?v=2l702a5sIJM', 5, '720', 'This video features clips from my FREE highly detailed Kicking Tutorials on this channel. There are 23 of them at the moment and ...', 'English', 752490, 'Tutorial', 'http://i.ytimg.com/vi/2l702a5sIJM/mqdefault.jpg', 'taekwondo, kick'),
(18, 'Taekwondo Kicking Techniques Sampler (taekwonwoo)', 'http://www.youtube.com/watch?v=2mv4hkrs0Q4', 2, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'English', 651933, 'Tutorial', 'http://i.ytimg.com/vi/2mv4hkrs0Q4/mqdefault.jpg', 'taekwondo'),
(19, 'Pro Taekwondo, Dong Lee vs Brian McCutcheon (1997)', 'http://www.youtube.com/watch?v=3ilZjltVed8', 8, '360', 'Taekwondo Profesional de finales de los 90. www.masTaekwondo.com Ver articulo: ...', 'English', 268253, 'Entertainment', 'http://i.ytimg.com/vi_webp/3ilZjltVed8/mqdefault.webp', 'taekwondo'),
(20, 'Patada al arbitro de los JJOO en taekwondo', 'http://www.youtube.com/watch?v=3nIrXiOK76w', 1, '480', 'fotos de la patada que un deportista cubano da al arbitro por ir perdiendo.', 'Non-English', 3232350, 'Entertainment', 'http://i.ytimg.com/vi/3nIrXiOK76w/mqdefault.jpg', 'taekwondo'),
(21, 'Taekwondo Jump Spin Hook Kick Tutorial', 'http://www.youtube.com/watch?v=3SaKycgcKfI', 10, '720', '"How to Jump Spinning Hook Kick Tutorial" Taekwondo Kickboxing " Jump Spin/Spinning Hook Kick" tutorial broken down and explained by me (Aaron Gassor), a 2nd Degree Black Belt in ITF Taekwon-do. I explain how for it to be effective in light/semi sparring, full contact and street fighting. Hope you benefit from the tutorial. I hope you like it :) ', 'English', 1412335, 'Tutorial', 'http://i.ytimg.com/vi/3SaKycgcKfI/mqdefault.jpg', 'taekwondo, hook kick, jump spin hook kick'),
(22, 'Taekwondo Axe Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=3Y64YN7dmP0', 11, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Axe Kick", effective in Kickboxing, MMA & Olympic style competition.', 'English', 162576, 'Tutorial', 'http://i.ytimg.com/vi/3Y64YN7dmP0/mqdefault.jpg', 'taekwondo, axe kick'),
(23, '5 Basic Taekwondo exercises for children. Gabriel ', 'http://www.youtube.com/watch?v=42ptqX4aF_E', 4, '720', 'This video has 5 basic Taekwondo exercises for children. It has been taught by the Olympic athlete Gabriel Mercedes. You will ...', 'English', 51654, 'Tutorial', 'http://i.ytimg.com/vi_webp/42ptqX4aF_E/mqdefault.webp', 'taekwondo'),
(24, 'Taekwondo Jump Side Kick Tutorial', 'http://www.youtube.com/watch?v=50RAVxgTeCY', 7, '1080', '"How to Jump/Flying Side Kick Tutorial" Taekwondo Kickboxing "Jump/Flying Side Kick" (Twigi/Twimyo Yop Chagi) tutorial broken ...', 'English', 52693, 'Tutorial', 'http://i.ytimg.com/vi/50RAVxgTeCY/mqdefault.jpg', 'taekwondo, jump side kick'),
(25, 'Tae Kwon Do fight in Korea', 'http://www.youtube.com/watch?v=530x1vuuuQw', 9, '240', 'Check out www.tkd360.com ! facebook for tkd people!', 'Non-English', 2322378, 'Entertainment,Application', 'http://i.ytimg.com/vi/530x1vuuuQw/mqdefault.jpg', 'taekwondo'),
(26, 'Taekwondo Speed Kicking Tutorial - How To Kick Fas', 'http://www.youtube.com/watch?v=55YOyLXEc1Q', 4, '720', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 133769, 'Tutorial', 'http://i.ytimg.com/vi/55YOyLXEc1Q/mqdefault.jpg', 'taekwondo, speed kick'),
(27, 'Taekwondo 540 Roundhouse Kick Tutorial (Kwonkicker', 'http://www.youtube.com/watch?v=5CMNDBtQuuw', 9, '720', 'This is a detailed Taekwondo Kickboxing tutorial for the "540 Jumping Spinning Circular Roundhouse Kick", effective in ...', 'English', 329025, 'Tutorial', 'http://i.ytimg.com/vi/5CMNDBtQuuw/mqdefault.jpg', 'taekwondo, kick'),
(28, 'Formidable exhibición de Taekwondo con los K Tigre', 'http://www.youtube.com/watch?v=5cUqqt0qbko', 10, '1080', 'http://taekwondoprogram.com Formidable exhibición de Taekwondo con los K Tigres de Korea ..', 'Non-English', 188569, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/5cUqqt0qbko/mqdefault.webp', 'taekwondo'),
(29, 'Taekwondo Jumping Back Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=5cxkTpVlVSI', 9, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Jumping Back Kick" (A.K.A. Jump Spinning Back Kick), effective in ...', 'English', 375685, 'Tutorial', 'http://i.ytimg.com/vi_webp/5cxkTpVlVSI/mqdefault.webp', 'taekwondo, back kick, jump back kick'),
(30, 'Phenomenal North Korean Taekwondo', 'http://www.youtube.com/watch?v=5l_b19VlzFI', 4, '360', 'They owe a lot to handsome Kim Jong-Il, the inventor of the kick. :) I can''t stop watching this video!', 'Non-English', 90452, 'Group demo', 'http://i.ytimg.com/vi_webp/5l_b19VlzFI/mqdefault.webp', 'taekwondo'),
(31, 'Koreans Training', 'http://www.youtube.com/watch?v=5xfivDk9L8Q', 3, '240', 'Koreans Regional Qualifiers Training hard for the 2007 nationals. These are Dae Jeon Competitors.', 'Non-English', 178877, 'Tutorial', 'http://i.ytimg.com/vi/5xfivDk9L8Q/mqdefault.jpg', 'taekwondo'),
(32, 'LOPEZ FAMILY DOMINATES USA TAEKWONDO TEAM--July 20', 'http://www.youtube.com/watch?v=6-EaUzDGT-U', 4, '240', 'A report by Al Jazeera''s Brendan Connor reports on the USA Taekwondo team that is headed for the 2008 Summer Olympics, and ...', 'English', 157158, 'Tutorial', 'http://i.ytimg.com/vi_webp/6-EaUzDGT-U/mqdefault.webp', 'taekwondo'),
(33, 'Taekwondo Poomsae 1 - 8', 'http://www.youtube.com/watch?v=6ELApKxX3qk', 7, '480', 'Poomsaes : * Taeguk Il Jang - Representa o Início * Taeguk I Jang - Representa a Virtude * Taeguk Sam Jang - Representa o ...', 'Non-English', 1010265, 'Tutorial', 'http://i.ytimg.com/vi_webp/6ELApKxX3qk/mqdefault.webp', 'taekwondo'),
(34, 'Tae Kwon Do Black Belt Test', 'http://www.youtube.com/watch?v=6tjFGPPllx8', 28, '1080', 'My black belt test, from Chas Tae Kwon Do Studio I have trained for almost 7 years and am really', 'English', 184288, 'Others', 'http://i.ytimg.com/vi_webp/6tjFGPPllx8/mqdefault.webp', 'taekwondo, black belt test'),
(35, 'TAEKWONDO KOREAN NATIONAL TEAM', 'http://www.youtube.com/watch?v=7-cjzfKMUhI', 7, '480', '', 'English', 211969, 'Entertainment', 'http://i.ytimg.com/vi_webp/7-cjzfKMUhI/mqdefault.webp', 'taekwondo'),
(36, 'Taekwondo Kickboxing Techniques Sampler on the BOB', 'http://www.youtube.com/watch?v=7ryQ-nhCnRY', 3, '720', 'Me doing some Taekwondo Kickboxing techniques on a B.O.B (270lbs Dummy). This is more of my Kickboxing techniques but i ...', 'English', 625627, 'Tutorial', 'http://i.ytimg.com/vi/7ryQ-nhCnRY/mqdefault.jpg', 'taekwondo'),
(37, 'Flexibility For Kicking Tutorial - For Stiff Peopl', 'http://www.youtube.com/watch?v=7zHWAbvShNM', 18, '480', 'This is a detailed flexibility for kicking tutorial. This tutorial focues on what stretches are needed (Front Splits & Side Splits) in order ...', 'English', 900674, 'Tutorial', 'http://i.ytimg.com/vi/7zHWAbvShNM/mqdefault.jpg', 'taekwondo, kick, stretch'),
(38, 'Taekwon-Do stretching in 5 min', 'http://www.youtube.com/watch?v=8eSUc-AdPME', 5, '480', 'Roy van de Donk IV dan International Instructor (ITF-Nederland) Een korte snelle dynamische warming-up zonder pauzes van 4 a ...', 'English', 130152, 'Tutorial', 'http://i.ytimg.com/vi_webp/8eSUc-AdPME/mqdefault.webp', 'taekwondo, stretch'),
(39, 'Taekwondo Jumping & Agility Training Tutorial (Kwo', 'http://www.youtube.com/watch?v=8f0r-MiX5bg', 17, '480', 'This is a detailed Taekwondo Kickboxing tutorial for basic jumping and agility training drills. Use these to increase the height of ...', 'English', 288488, 'Tutorial', 'http://i.ytimg.com/vi/8f0r-MiX5bg/mqdefault.jpg', 'taekwondo, jump'),
(40, 'Taekwondo VS Karate - Knockout 2014', 'http://www.youtube.com/watch?v=8fXqKVyPzyM', 5, '240', 'Watch the best Martial Videos here►►► http://www.TaeSpeed.it', 'Non-English', 669530, 'Entertainment', 'http://i.ytimg.com/vi/8fXqKVyPzyM/mqdefault.jpg', 'taekwondo'),
(41, 'taekwondo KO best', 'http://www.youtube.com/watch?v=8Y3-STuMbVE', 4, '144', 'I got the music from here: http://www.youtube.com/trackonerecord... If you liked the old song better, you can get it yourself from audioswap - search for "With A Spirit" by 009 Sound System', 'English', 8492949, 'Entertainment', 'http://i.ytimg.com/vi/8Y3-STuMbVE/mqdefault.jpg', 'taekwondo'),
(42, 'Taekwondo Revolution of kicking jumping side kick', 'http://www.youtube.com/watch?v=9goULN3sNRg', 5, '240', 'A clip form Revolution of Kicking - Jumping side kick.', 'Non-English', 225104, 'Tutorial', 'http://i.ytimg.com/vi/9goULN3sNRg/mqdefault.jpg', 'taekwondo, jump side kick'),
(44, 'AWESOME 8 YEAR OLD TAEKWONDO TRAINING!!.wmv', 'http://www.youtube.com/watch?v=A6Njko_PUo0', 6, '360', '8 YEAR OLD GIRL TRAINS WITH MASTER IN TAEKWONDO.', 'English', 170869, 'Tutorial,Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/A6Njko_PUo0/mqdefault.webp', 'taekwondo'),
(45, 'Taekwondo : Le club d''Ekvara Kamkasoumphou !', 'http://www.youtube.com/watch?v=AA45xf0m13U', 4, '1080', 'Ekvara Kamkasoumphou est l''un de nos plus célèbres champions de Taekwondo. Après avoir passé 16 ans en équipe de France ..', 'Non-English', 173337, 'Tutorial,Group demo', 'http://i.ytimg.com/vi_webp/AA45xf0m13U/mqdefault.webp', 'taekwondo'),
(46, 'How to Do Basic Sitting Stretches | Taekwondo Trai', 'http://www.youtube.com/watch?v=aEYgYkdr42Y', 3, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 124685, 'Tutorial', 'http://i.ytimg.com/vi/aEYgYkdr42Y/mqdefault.jpg', 'taekwondo, sitting stretch'),
(47, 'How to Do a Spinning Hook Kick | Taekwondo Trainin', 'http://www.youtube.com/watch?v=Avr54VCNMXY', 1, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 112685, 'Tutorial', 'http://i.ytimg.com/vi/Avr54VCNMXY/mqdefault.jpg', 'taekwondo, spinning hook kick'),
(48, 'Taekwondo Leg Drills For Better Kicking Control an', 'http://www.youtube.com/watch?v=ay2pTJGxtlU', 5, '720', 'How to Improve Leg Control and Strength for Kicking Tutorial Some quick and effective Taekwondo/Kickboxing exercises to ...', 'English', 132195, 'Tutorial', 'http://i.ytimg.com/vi/ay2pTJGxtlU/mqdefault.jpg', 'taekwondo, kick'),
(49, 'Ktigers Taekwondo Promotion Film', 'http://www.youtube.com/watch?v=b1G3vCyjkfE', 5, '240', 'Korean Tigers Team Taekwondo.', 'Non-English', 966936, 'Group demo', 'http://i.ytimg.com/vi/b1G3vCyjkfE/mqdefault.jpg', 'taekwondo'),
(51, 'How to Do the Face Block Technique | Taekwondo Tra', 'http://www.youtube.com/watch?v=BJ0jVqIPXFM', 2, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 69263, 'Tutorial', 'http://i.ytimg.com/vi/BJ0jVqIPXFM/mqdefault.jpg', 'taekwondo, face block'),
(52, 'SPIDER-MAN Taekwondo | Kickboxing (original)', 'http://www.youtube.com/watch?v=bjd3AAxa73s', 5, '1080', 'You can visit us online at: https://www.facebook.com/pages/Pecoraros-Fitness-Kickboxi... ...', 'English', 5917190, 'Entertainment', 'http://i.ytimg.com/vi/bjd3AAxa73s/mqdefault.jpg', 'taekwondo'),
(53, 'Taekwondo Training Camp in Korea 2011 [No Music]', 'http://www.youtube.com/watch?v=bNbSAUZyBow', 11, '720', 'Re-uploaded with no background music! Featured Schools: Ganghwa Junior/Middle/Senior School Tong-Jin High School Son-In ...', 'Non-English', 302136, 'Tutorial,Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/bNbSAUZyBow/mqdefault.webp', 'taekwondo, training camp'),
(54, 'Tae Kwon-Do White Belt Test', 'http://www.youtube.com/watch?v=BqxNffnIJJw', 2, '1080', 'Tae Kwon-Do Test: October 3, 2010. Janel, Colin, Andy, and Khoa (white belt) performing the pattern Chon Ji at Duc Dang Tae ...', 'Non-English', 238120, 'Others', 'http://i.ytimg.com/vi_webp/BqxNffnIJJw/mqdefault.webp', 'taekwondo, white belt test'),
(55, 'Taekwondo Full Roundhouse Kick Tutorial (Kwonkicke', 'http://www.youtube.com/watch?v=bSzvkAydKuM', 13, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Full Roundhouse Kick" (not to be confused with the linear "Round ...', 'English', 296046, 'Tutorial', 'http://i.ytimg.com/vi/bSzvkAydKuM/mqdefault.jpg', 'taekwondo, round house kick'),
(56, 'Taekwondo Jumping Roundhouse Kick', 'http://www.youtube.com/watch?v=bvCmyW0WOPo', 4, '480', 'Learn how to execute taekwondo''s jumping or aero roundhouse kick - a great technique for board breaking demonstrations.', 'English', 437199, 'Group demo', 'http://i.ytimg.com/vi_webp/bvCmyW0WOPo/mqdefault.webp', 'taekwondo, round house kick'),
(57, 'Carrera Universitaria de Taekwondo - Promo', 'http://www.youtube.com/watch?v=Byfmy6IKEnM', 5, '1080', 'Hwashin Cyber University International Taekwondo Department INFO: http://mastaekwondo.com/tag/hscu/', 'Non-English', 115501, 'Tutorial', 'http://i.ytimg.com/vi_webp/Byfmy6IKEnM/mqdefault.webp', 'taekwondo'),
(58, 'Taekwondo 540/c720 Hook Kick Tutorial', 'http://www.youtube.com/watch?v=c1RBgLxPZuk', 9, '720', 'First of all this kick is not for fighting, it is a flashy move and to show your that you can do more advanced kicks. So NO haters ..', 'English', 270750, 'Tutorial', 'http://i.ytimg.com/vi/c1RBgLxPZuk/mqdefault.jpg', 'taekwondo'),
(59, '[Taekwondo] Super Kicks (Master''s Cut)', 'http://www.youtube.com/watch?v=c6DftzVPEVY', 7, '720', 'Turning Kick for basic attack and defense Kick 25 http://youtu.be/_45zOfSUdyQ Kick 24 http://youtu.be/-DTxjRIojV4 Kick 23 ...', 'Non-English', 248985, 'Tutorial', 'http://i.ytimg.com/vi_webp/c6DftzVPEVY/mqdefault.webp', 'taekwondo, Turning Kick'),
(60, 'Taekwondo técnicas de contraataque [TKD WTF] 2 de ', 'http://www.youtube.com/watch?v=CIa6amN7gmM', 15, '480', 'Un video de taekwondo wtf.', 'Non-English', 574222, 'Group demo', 'http://i.ytimg.com/vi_webp/CIa6amN7gmM/mqdefault.webp', 'taekwondo'),
(62, 'Awesome Performance - South Korean Taekwondo Demo ', 'http://www.youtube.com/watch?v=cOEMI4yeLK8', 12, '1080', 'The South Korean Taekwondo Demo Team performs at Kim''s White Tiger in Burlington, NC.', 'English', 53324, 'Group demo', 'http://i.ytimg.com/vi_webp/cOEMI4yeLK8/mqdefault.webp', 'taekwondo'),
(63, 'Taekwondo Practice', 'http://www.youtube.com/watch?v=crtyYpZYfDs', 10, '480', '', 'English', 629569, 'Tutorial', 'http://i.ytimg.com/vi_webp/crtyYpZYfDs/mqdefault.webp', 'taekwondo'),
(64, '2014 WTF World Junior Championships Opening Ceremo', 'http://www.youtube.com/watch?v=D29GHzwlWus', 23, '480', '2014 WTF World Junior Championships Opening Ceremony Taekwondo Demonstrati', 'Non-English', 59696, 'Group demo', 'http://i.ytimg.com/vi/D29GHzwlWus/mqdefault.jpg', 'taekwondo, 2014 WTF'),
(65, 'Taekwondo Kicks : Taekwondo Reverse Hook Kick', 'http://www.youtube.com/watch?v=d7g2gzoqK14', 1, '480', 'The taekwondo reverse hook kick is a powerful knockout kick in martial arts. Learn the reverse hook kick from a taekwondo expert ...', 'English', 73641, 'Tutorial', 'http://i.ytimg.com/vi/d7g2gzoqK14/mqdefault.jpg', 'taekwondo, reverse hook kick'),
(66, 'Taekwondo Hook Kick Tutorial', 'http://www.youtube.com/watch?v=Db098oKgzpk', 12, '720', '"How to Hook Kick Tutorial" Taekwondo Kickboxing "Hook Kick" tutorial broken down and explained by me (Aaron Gassor), a 2nd ...', 'English', 89554, 'Tutorial', 'http://i.ytimg.com/vi/Db098oKgzpk/mqdefault.jpg', 'taekwondo, hook kick'),
(67, 'Taekwondo Quadruple kick.', 'http://www.youtube.com/watch?v=DFnx2kv11tU', 1, '720', 'Want To Make money Online Click Here http://adf.ly/qW1hu Invest $1 And Receive $1.55 100$ Gurranted. Click Below And Earn ...', 'English', 486428, 'Others', 'http://i.ytimg.com/vi/DFnx2kv11tU/mqdefault.jpg', 'taekwondo'),
(68, 'Learn all kicks taekwondo (18 kick) (تعلم كل ركلات', 'http://www.youtube.com/watch?v=DHP4wN1W4K0', 10, '480', '', 'Non-English', 190939, 'Tutorial', 'http://i.ytimg.com/vi_webp/DHP4wN1W4K0/mqdefault.webp', 'taekwondo, kick'),
(69, 'Taekwon-do ITF Reverse Turning Kick by Master V. A', 'http://www.youtube.com/watch?v=DYcsS6b4kxo', 7, '480', 'A Seminar in Krete, Hellas(Greece) where Master Alexandris is teaching the fundamentals of Bandae Dollyo Chagi (Reverse ...', 'Non-English', 76384, 'Tutorial', 'http://i.ytimg.com/vi_webp/DYcsS6b4kxo/mqdefault.webp', 'taekwondo, Reverse Turning Kick'),
(70, 'Human Weapon - Tae Kwon Do - Tornado Kick', 'http://www.youtube.com/watch?v=E4ZE9Ivs9Kc', 2, '240', 'This is a Technique shown from the TV Show HUMAN WEAPON which airs Fridays on The History Channel, CHeck your local ...', 'English', 2631441, 'Tutorial', 'http://i.ytimg.com/vi/E4ZE9Ivs9Kc/mqdefault.jpg', 'taekwondo, kick'),
(71, 'Taekwondo 360 Hook Kick Tutorial', 'http://www.youtube.com/watch?v=E6PA8vieZUc', 6, '720', '"How to 360 Hook Kick Tutorial" Taekwondo Kickboxing " 360 Hook Kick" tutorial broken down and explained by me (Aaron ...', 'English', 69964, 'Tutorial', 'http://i.ytimg.com/vi/E6PA8vieZUc/mqdefault.jpg', 'taekwondo, hook kick'),
(72, 'How to Do a Double Roundhouse Kick | Taekwondo Tra', 'http://www.youtube.com/watch?v=e9qfasu0DaA', 3, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 52374, 'Tutorial', 'http://i.ytimg.com/vi/e9qfasu0DaA/mqdefault.jpg', 'taekwondo, double roundhouse kick'),
(73, 'Yamasaki Yuki, Japan''s Number 1 Taekwondo Fighter', 'http://www.youtube.com/watch?v=eCa3VvJRWks', 4, '480', 'http://yu-ki.main.jp/ Yamasaki Yuki, Japan''s Number 1 Taekwondo Fighter ! He is really crazy ! He is coming soon!', 'Non-English', 85685, 'Entertainment', 'http://i.ytimg.com/vi_webp/eCa3VvJRWks/mqdefault.webp', 'taekwondo'),
(74, 'Taekwondo 360 Spin Hook Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=edz1SGOOuH0', 4, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "360 Spinning Hook Kick", effective in Kickboxing, MMA & Olympic style ...', 'English', 180756, 'Tutorial', 'http://i.ytimg.com/vi/edz1SGOOuH0/mqdefault.jpg', 'taekwondo, hook kick'),
(75, 'Taekwondo kid - Frederik Emil Olsen. (Denmark)', 'http://www.youtube.com/watch?v=EKM02vdA4_c', 6, '360', 'Taekwondo kid (Denmar', 'Non-English', 308000, 'Group demo', 'http://i.ytimg.com/vi_webp/EKM02vdA4_c/mqdefault.webp', 'taekwondo'),
(77, 'K Tigers Taekwondo', 'http://www.youtube.com/watch?v=ENKh-1qUvJA', 3, '1080', 'The K Tigers are a demo team who are renowned for there aerobatic stunts and outstanding technique.', 'English', 492668, 'Group demo', 'http://i.ytimg.com/vi_webp/ENKh-1qUvJA/mqdefault.webp', 'taekwondo'),
(78, 'Kukkiwon Taekwondo Demonstration (2013 Belgian Ope', 'http://www.youtube.com/watch?v=EO8eP6BTyrs', 31, '1080', 'Kukkiwon Taekwondo Demonstration at Belgian Open 2013 edition: about the same as 2012 edition with some bonus though', 'Non-English', 252967, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/EO8eP6BTyrs/mqdefault.webp', 'taekwondo'),
(79, 'Taekwondo dance - sorry sorry (Super Junior)', 'http://www.youtube.com/watch?v=F2YmAOfTKnQ', 2, '480', 'A taekwondo master from Korea teaching taekwondo students how to dance sorry sorry (by Super Junior) during Poomsae ...', 'Non-English', 137414, 'Entertainment', 'http://i.ytimg.com/vi/F2YmAOfTKnQ/mqdefault.jpg', 'taekwondo'),
(80, 'Tae Kwon Do Vs Muay Thai', 'http://www.youtube.com/watch?v=fL9ZXos8LfQ', 1, '240', 'a know you cant compare a Martial Arts to which is better, only fighters', 'Non-English', 10146520, 'Entertainment', 'http://i.ytimg.com/vi/fL9ZXos8LfQ/mqdefault.jpg', 'taekwondo'),
(81, 'TAEKWONDO ESPAÑOL EXIBICIÓN', 'http://www.youtube.com/watch?v=fMhYnF2SFKs', 3, '480', 'BUENA DEMOSTRACIÓN DEL TAEKWONDO GALLEGUIÑO, Y LES DEJO ESTE LINK DE OTRO VIDEO QUE HICE CON LO ...', 'Non-English', 378055, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/fMhYnF2SFKs/mqdefault.webp', 'taekwondo'),
(82, 'Taekwondo Round House Kick Tutorial (taekwonwoo) 태', 'http://www.youtube.com/watch?v=fWlibj8awtI', 4, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'Non-English', 166469, 'Tutorial', 'http://i.ytimg.com/vi/fWlibj8awtI/mqdefault.jpg', 'taekwondo, round house kick'),
(83, 'Olympic Taekwondo Coach Paul Green Kicking Speed A', 'http://www.youtube.com/watch?v=fwWaMrMEM6s', 2, '1080', 'http://realworldtaekwondo.com/Dynamic.html Jade Jones'' had Olympic Taekwondo coach Paul Green in her corner when she won ...', 'English', 124768, 'Tutorial', 'http://i.ytimg.com/vi_webp/fwWaMrMEM6s/mqdefault.webp', 'taekwondo, kick'),
(84, 'Olympic Taekwondo Sparring Tips and Techniques', 'http://www.youtube.com/watch?v=Fy6vGFz1E60', 4, '480', 'To view the first video in this series click: http://www.monkeysee.com/play/6520-basic-olympic-taekwondo.', 'English', 125356, 'Tutorial', 'http://i.ytimg.com/vi/Fy6vGFz1E60/mqdefault.jpg', 'taekwondo'),
(85, 'TAEKWONDO TRAINING FOR KIDS', 'http://www.youtube.com/watch?v=g0TLPVK7qSQ', 5, '480', 'The development of agility and speed in the children''s category is very important for the future of taekwondo athlete.', 'English', 152599, 'Tutorial', 'http://i.ytimg.com/vi_webp/g0TLPVK7qSQ/mqdefault.webp', 'taekwondo'),
(86, 'The power kicks in Taekwondo', 'http://www.youtube.com/watch?v=Gnu94B6Edrs', 7, '360', 'Taekwondo kicks 220km per hour. Taekwondo kicks destructive 1040kg', 'English', 4077800, 'Entertainment,Application', 'http://i.ytimg.com/vi/Gnu94B6Edrs/mqdefault.jpg', 'taekwondo, power kick'),
(87, 'Taekwondo Polska rapid Śrem "street impact"', 'http://www.youtube.com/watch?v=GUCi614pnJc', 3, '1080', '', 'Non-English', 79023, 'Entertainment', 'http://i.ytimg.com/vi_webp/GUCi614pnJc/mqdefault.webp', 'taekwondo'),
(88, 'Taekwondo Front Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=GvmczzIN7RY', 8, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the basic "Front Kick" (not to be confused with the "Push/Stomp Kick"), ...', 'English', 83826, 'Tutorial', 'http://i.ytimg.com/vi/GvmczzIN7RY/mqdefault.jpg', 'taekwondo'),
(89, 'Taekwondo vs Kickboxing', 'http://www.youtube.com/watch?v=h0VAH3tUQsg', 2, '360', 'Taekwondo vs Kickboxing.', 'Non-English', 526656, 'Entertainment', 'http://i.ytimg.com/vi_webp/h0VAH3tUQsg/mqdefault.webp', 'taekwondo, kickboxing'),
(90, 'Taekwondo, collection of the best kicks', 'http://www.youtube.com/watch?v=H48XGX0L5DI', 4, '480', 'Taekwondo, mixed youtube videos collected.', 'English', 2169920, 'Entertainment,Application', 'http://i.ytimg.com/vi_webp/H48XGX0L5DI/mqdefault.webp', 'taekwondo'),
(91, 'Taekwondo Kickboxing Techniques Sampler (Kwonkicke', 'http://www.youtube.com/watch?v=H7ntN_fd6oQ', 4, '480', '(This is a re-upload of an older sampler, now without copyright issues!)  This is a sampler featuring techniques from my various martial arts tutorials and training videos. I''ve uploaded tutorials on the majority of the techniques featured in this video . Check my playlists section on my youtube channel to watch them. ', 'English', 1398189, 'Tutorial,Application', 'http://i.ytimg.com/vi/H7ntN_fd6oQ/mqdefault.jpg', 'taekwondo, kickboxing'),
(92, 'Patadas (Chagi) TaeKwonDo [Español]', 'http://www.youtube.com/watch?v=h8gkh2Eq9kU', 5, '240', 'Patas Basicas de TaeKwonDo.', 'Non-English', 88114, 'Tutorial', 'http://i.ytimg.com/vi_webp/h8gkh2Eq9kU/mqdefault.webp', 'taekwondo'),
(93, 'Toronto Taekwondo Kicks/Skills', 'http://www.youtube.com/watch?v=hXhZVh07Qxs', 3, '720', 'WORLD TAEKWONDO FEDERATION: OFFICIAL SCHOOL WEBSITE: !! www.rimstkd.ca !! INSTAGRAM:', 'English', 403835, 'Tutorial', 'http://i.ytimg.com/vi/hXhZVh07Qxs/mqdefault.jpg', 'taekwondo'),
(94, '4/4 Korean National Taekwondo Demonstration Team -', 'http://www.youtube.com/watch?v=I13Z6ozclhY', 6, '360', 'Trop fort!', 'English', 68112, 'Entertainment', 'http://i.ytimg.com/vi_webp/I13Z6ozclhY/mqdefault.webp', 'taekwondo'),
(95, '100 Taekwondo speed kicks in 66seconds (taekwonwoo', 'http://www.youtube.com/watch?v=i4DgKkmgvWI', 2, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'English', 602220, 'Tutorial', 'http://i.ytimg.com/vi/i4DgKkmgvWI/mqdefault.jpg', 'taekwondo, speed kick'),
(96, 'Karate VS WTF Taekwondo', 'http://www.youtube.com/watch?v=Iedxtg0N_KE', 5, '240', 'Body shot again......', 'English', 5411180, 'Entertainment,Application', 'http://i.ytimg.com/vi/Iedxtg0N_KE/mqdefault.jpg', 'taekwondo, karate'),
(97, 'Taekwondo - fly kick', 'http://www.youtube.com/watch?v=IGuOcrw_ETs', 2, '240', 'Taekwondo - fly kick', 'English', 5271620, 'Entertainment,Application', 'http://i.ytimg.com/vi/IGuOcrw_ETs/mqdefault.jpg', 'taekwondo, fly kick'),
(98, 'Tricking battles and extreme Taekwondo - Red Bull ', 'http://www.youtube.com/watch?v=IHY8mol-v2A', 2, '1080', 'Red Bull Kick It 2013 was held in K-Art Hall in South Korea on June 29th, 2013. 5 judges decided the fate of advanced martial artists and karate professionals. Martial artist, Andy Le, took first followed by Donavan Sheehan in 2nd place. ', 'English', 4097693, 'Entertainment,Application', 'http://i.ytimg.com/vi/IHY8mol-v2A/mqdefault.jpg', 'taekwondo'),
(99, 'Highest TaeKwondo Kick - Guinness World Record', 'http://www.youtube.com/watch?v=iRpOQC4sBbI', 7, '360', 'Pascal Gentil (May 15, 1973) from France has the world record for the highest TaeKwonDo kick in the world (2005). Over 2.60 meters or 8.6 feet. (Sorry for the bad quality)', 'Non-English', 1566725, 'Others', 'http://i.ytimg.com/vi_webp/iRpOQC4sBbI/mqdefault.webp', 'taekwondo, kick'),
(100, 'Taekwondo Basic Upper Body Strength Drills (Kwonki', 'http://www.youtube.com/watch?v=iYt2-AtyYkI', 10, '480', 'This is a detailed Taekwondo Kickboxing tutorial for basic upper body & core strength drills. These push-up drills will help ...', 'English', 176871, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/iYt2-AtyYkI/mqdefault.jpg', 'taekwondo, strength drill'),
(101, 'Taekwondo Reverse Hook Kick Tutorial (taekwonwoo)', 'http://www.youtube.com/watch?v=J8JdW-iEbg4', 3, '720', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ..', 'English', 80793, 'Tutorial', 'http://i.ytimg.com/vi/J8JdW-iEbg4/mqdefault.jpg', 'taekwondo, reverse hook kick'),
(102, 'Taekwondo Sparring Quick Tip 3 : Make your back ki', 'http://www.youtube.com/watch?v=jAm-BkZotew', 5, '720', 'What''s your TKD training challenge? Let http://www.taekwonwoo.net find the most effective and affordable online taekwondo ... HD', 'English', 59969, 'Tutorial', 'http://i.ytimg.com/vi/jAm-BkZotew/mqdefault.jpg', 'taekwondo, back kick'),
(103, 'Taekwondo WTF training', 'http://www.youtube.com/watch?v=JdoFVEXpBpw', 9, '240', 'Taekwondo WTF training.', 'English', 133548, 'Tutorial', 'http://i.ytimg.com/vi_webp/JdoFVEXpBpw/mqdefault.webp', 'taekwondo'),
(104, 'Olympic Taekwondo best of', 'http://www.youtube.com/watch?v=jKTRqvW1IMU', 7, '480', 'Olympic Taekwondo , the best action!', 'English', 11206169, 'Entertainment', 'http://i.ytimg.com/vi/jKTRqvW1IMU/mqdefault.jpg', 'taekwondo, olympic'),
(105, 'Flexibility for Martial Arts Tutorial (Get High Ki', 'http://www.youtube.com/watch?v=jO84APlNN9s', 11, '720', 'Me (Aaron Gassor, a 2nd Degree Black Belt in Taekwondo) taking you through some basic stretches and showing how you can ...', 'English', 948267, 'Tutorial', 'http://i.ytimg.com/vi/jO84APlNN9s/mqdefault.jpg', 'taekwondo, stretch, '),
(106, 'How to Do a Tornado Roundhouse Kick | Taekwondo Tr', 'http://www.youtube.com/watch?v=JrUeTiTAkWw', 1, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 75096, 'Tutorial', 'http://i.ytimg.com/vi/JrUeTiTAkWw/mqdefault.jpg', 'taekwondo, kick, tornado roundhouse kick'),
(107, 'Taekwondo Revolution of kicking axe kick', 'http://www.youtube.com/watch?v=jXiUo2LgoO8', 6, '240', 'axe Kick - Rip from Revolution of Kicking.', 'Non-English', 234396, 'Tutorial', 'http://i.ytimg.com/vi/jXiUo2LgoO8/mqdefault.jpg', 'taekwondo, axe kick'),
(108, 'Taekwondo Double Round Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=k_DSH8ReNh8', 10, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Double Roundhouse Kick" (and a few of its variations), effective in ', 'English', 154256, 'Tutorial', 'http://i.ytimg.com/vi/k_DSH8ReNh8/mqdefault.jpg', 'taekwondo, double round kick'),
(109, 'Advanced Tae Kwon Do Kicks & Punches : Tae Kwon Do', 'http://www.youtube.com/watch?v=k0MfvjRQrGE', 2, '240', 'Learn the tae kwon do combination move: jab reverse punch evading mid-air back kick in advanced tae kwon do from a martial ...', 'English', 60493, 'Tutorial', 'http://i.ytimg.com/vi/k0MfvjRQrGE/mqdefault.jpg', 'taekwondo, kick, punch'),
(110, 'Taekwondo Skipping Jumping Back Kick Tutorial (tae', 'http://www.youtube.com/watch?v=KAT5ye-iHNA', 3, '720', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 58830, 'Tutorial', 'http://i.ytimg.com/vi/KAT5ye-iHNA/mqdefault.jpg', 'taekwondo, back kick'),
(111, 'Taekwondo Side Kick Tutorial (taekwonwoo) 태권도 옆차기', 'http://www.youtube.com/watch?v=kdr4jpvqQzw', 4, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'English', 195881, 'Tutorial', 'http://i.ytimg.com/vi/kdr4jpvqQzw/mqdefault.jpg', 'taekwondo, side kick'),
(112, 'Taekwondo: Secrets of skipping side kick (taekwonw', 'http://www.youtube.com/watch?v=koDEbmhPn0I', 12, '1080', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 894845, 'Tutorial', 'http://i.ytimg.com/vi/koDEbmhPn0I/mqdefault.jpg', 'taekwondo'),
(113, 'How to Do Back Kick & Jump Back Kick | Taekwondo T', 'http://www.youtube.com/watch?v=Kuq1H1Y-BCA', 3, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 59737, 'Tutorial', 'http://i.ytimg.com/vi/Kuq1H1Y-BCA/mqdefault.jpg', 'taekwondo, jump back kick,kick'),
(114, 'Taekwondo Outside Crescent Kick Tutorial (Kwonkick', 'http://www.youtube.com/watch?v=kXqJmBzT6PQ', 4, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Outside Crescent Kick" (a.k.a. "Outside to Inside Crescent Kick"), effective ...', 'English', 50864, 'Tutorial', 'http://i.ytimg.com/vi/kXqJmBzT6PQ/mqdefault.jpg', 'taekwondo. crescent kick, outside crescent kick'),
(115, 'Master Kwon''s Full Contact Taekwondo(FCT) sparring', 'http://www.youtube.com/watch?v=lBJVjIBSiqU', 4, '480', 'This is a re-upload of an older sampler, now without copyright issues!) This is a sampler featuring techniques from my various ...', 'English', 1403256, 'Tutorial', 'http://i.ytimg.com/vi/H7ntN_fd6oQ/mqdefault.jpg', 'taekwondo'),
(116, 'WTF Taekwondo Training Balance and Speed', 'http://www.youtube.com/watch?v=LG8J8I0Pvd8', 2, '240', 'WTF Taekwondo Training.', 'English', 220124, 'Tutorial', 'http://i.ytimg.com/vi/LG8J8I0Pvd8/mqdefault.jpg', 'taekwondo'),
(117, 'HUMAN WEAPON TAEKWONDO TECHNIQUES', 'http://www.youtube.com/watch?v=lV4Sf3sSCOY', 2, '240', 'all about taekwondo techniques on Human Weapon.', 'English', 103956, 'Tutorial', 'http://i.ytimg.com/vi_webp/lV4Sf3sSCOY/mqdefault.webp', 'taekwondo, kick'),
(118, 'TAEKWONDO TRAINING 100% PHYSICA', 'http://www.youtube.com/watch?v=lXZGX563Orc', 3, '480', 'PREPARE FOR COMBAT Exercises to develop speed, agility and strength in the taekwondo athlete.', 'English', 176007, 'Tutorial', 'http://i.ytimg.com/vi_webp/lXZGX563Orc/mqdefault.webp', 'taekwondo, physical training'),
(119, 'Taekwondo & MMA Sampler on the Versys VS.1', 'http://www.youtube.com/watch?v=M2hYZQJfrS8', 3, '720', 'Me training on the new Versys VS.1 by Century. Thought I''d mix it up a bit with some ground fighting and drills. Some of the moves ...', 'English', 455093, 'Tutorial', 'http://i.ytimg.com/vi/M2hYZQJfrS8/mqdefault.jpg', 'taekwondo'),
(120, 'Taekwondo 540 Kick Tutorial', 'http://www.youtube.com/watch?v=m5DocuF1vHo', 9, '720', 'First of all this kick is not for fighting, it is a flashy move and to show your that you can do more advanced kicks. So NO haters .', 'English', 670166, 'Tutorial', 'http://i.ytimg.com/vi/m5DocuF1vHo/mqdefault.jpg', 'taekwondo'),
(121, 'How to Taekwondo kick FASTER tutorial (taekwonwoo)', 'http://www.youtube.com/watch?v=McqhEl-aNZQ', 3, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'English', 230977, 'Tutorial', 'http://i.ytimg.com/vi/McqhEl-aNZQ/mqdefault.jpg', 'taekwondo, kick'),
(122, 'Asian games 2014 Taekwondo -63kg Gold medal final ', 'http://www.youtube.com/watch?v=mIdbxJzSpTk', 10, '720', 'Korea: Lee Dae Hoon Thailand: Akkarin Kitwijarn Taekwondo Demonstration :http://goo.gl/BQYYpQ Taekwondo Grand P', 'Non-English', 128706, 'Entertainment', 'http://i.ytimg.com/vi/mIdbxJzSpTk/mqdefault.jpg', 'taekwondo, asian games 2014, gold metal final'),
(123, 'Taekwondo Kicks and Sparring Techniques', 'http://www.youtube.com/watch?v=MvPPssY7jDk', 1, '240', 'http://www.black-eagle.co.uk/ This video shows various themes specific to Taekwondo, such as distance in a fight, blocks, moving, ...', 'English', 760253, 'Tutorial', 'http://i.ytimg.com/vi/MvPPssY7jDk/mqdefault.jpg', 'taekwondo, kick'),
(124, 'Taekwondo Kicks : Taekwondo Crescent Kicks', 'http://www.youtube.com/watch?v=N0qnEmIlnU8', 2, '480', 'The crescent kick is a great kick to add to your taekwondo arsenal. Learn to perform the crescent kick from a taekwondo expert in ...', 'English', 82515, 'Tutorial', 'http://i.ytimg.com/vi/N0qnEmIlnU8/mqdefault.jpg', 'taekwondo, crescent kick'),
(125, 'Taekwondo Training in Korea (SKKU Sung Kyun Kwan U', 'http://www.youtube.com/watch?v=N0YdYutitZk', 8, '360', 'Moohwa Facebook http://www.facebook.com/MoohwaTaekwondoTeam Moohwa Official Website http://www.moohwa.net My ...', 'English', 149827, 'Tutorial', 'http://i.ytimg.com/vi_webp/N0YdYutitZk/mqdefault.webp', 'taekwondo'),
(126, '720 taekwondo kick 4 targets', 'http://www.youtube.com/watch?v=n7EF3v4EzQU', 1, '360', 'practicing 720 kick 4 targets yim jaehyun of ultimate tkd and mteam :)', 'English', 63766, 'Group demo', 'http://i.ytimg.com/vi_webp/n7EF3v4EzQU/mqdefault.webp', 'taekwondo, 720 kick'),
(127, 'The Way of Tae Kwon Do part 1', 'http://www.youtube.com/watch?v=naSzzVeNKFM', 10, '240', 'A Korean documentary about Tae Kwon Do featuring the Il~Do and Elite Fitness schools in Irvine California. Grandmaster Kang''s ...', 'Non-English', 50433, 'Tutorial', 'http://i.ytimg.com/vi_webp/naSzzVeNKFM/mqdefault.webp', 'taekwondo'),
(128, 'How to tie your Taekwondo Belt Correctly.', 'http://www.youtube.com/watch?v=nCnu_mVHg9I', 3, '1080', 'Taekwondo Uniform, How to tie your Tae Kwon Do belt correctly. Master Joe talks you through how to put your belt on correctly.', 'English', 321876, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi_webp/nCnu_mVHg9I/mqdefault.webp', 'taekwondo, uniform, belt'),
(129, 'Taekwondo Master', 'http://www.youtube.com/watch?v=NdWtNLkxg3c', 1, '240', 'Great demonstration', 'English', 3848182, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/NdWtNLkxg3c/mqdefault.jpg', 'Entertainment'),
(130, 'Taekwondo vs Kickboxing', 'http://www.youtube.com/watch?v=nH0dCP4nDzU', 5, '240', 'Genki Sudo vs Korean Medalist of Taekwondo in K-1 WORLD-MAX 2002 International showdonwn (2002/10/11).', 'Non-English', 6611628, 'Entertainment', 'http://i.ytimg.com/vi/nH0dCP4nDzU/mqdefault.jpg', 'taekwondo, kickboxing'),
(131, 'Aikido VS Taekwondo', 'http://www.youtube.com/watch?v=NinO0vGum38', 2, '480', 'Aikido vs taekwondo', 'English', 5199987, 'Application', 'http://i.ytimg.com/vi_webp/NinO0vGum38/mqdefault.webp', 'taekwondo, aikido'),
(132, 'How to Do a Bolley Kick | Taekwondo Training', 'http://www.youtube.com/watch?v=nNyV0GgL2lU', 2, '1080', 'Watch more How to Do Taekwondo videos: .', 'English', 207465, 'Tutorial', 'http://i.ytimg.com/vi/nNyV0GgL2lU/mqdefault.jpg', 'taekwondo, bolley kick'),
(133, 'Philippines vs Singapore - 26th SEA Games Taekwond', 'http://www.youtube.com/watch?v=NQrIjkVGdvI', 10, '240', 'Japoy Lizardo of the Philippines won over Singapore in the 26th SEA Games held in Jakarta, Indonesia.', 'English', 233826, 'Entertainment', 'http://i.ytimg.com/vi_webp/NQrIjkVGdvI/mqdefault.webp', 'taekwondo'),
(134, 'Taekwondo: How to Improve Reaction Time in Taekwon', 'http://www.youtube.com/watch?v=nsFMygfDJYA', 6, '480', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'English', 151846, 'Tutorial', 'http://i.ytimg.com/vi/nsFMygfDJYA/mqdefault.jpg', 'taekwondo'),
(135, 'Taekwondo workout', 'http://www.youtube.com/watch?v=NTwPEfMUauw', 33, '480', '30 minute workout with kicks and exercises. If you can''t do the moves, get along to your local Taekwondo class.', 'English', 100656, 'Tutorial', 'http://i.ytimg.com/vi_webp/NTwPEfMUauw/mqdefault.webp', 'taekwondo'),
(136, 'Exo [중독(overdose)] taekwondo performance! Dancing9', 'http://www.youtube.com/watch?v=oF42bC8z-I0', 2, '720', '댄싱9에서 펼친 K타이거즈의 엑소 중독 퍼포먼스!! 댄싱9 예고편 Official FB : www.facebook.com/koreantigers.', 'Non-English', 226993, 'Entertainment', 'http://i.ytimg.com/vi_webp/oF42bC8z-I0/mqdefault.webp', 'taekwondo, Dance'),
(137, 'Advanced Tae Kwon Do Kicks & Punches : Tae Kwon Do', 'http://www.youtube.com/watch?v=oZCOHHSO0UM', 2, '240', 'Learn how to fight two opponents using the flying two direction kick in advanced tae kwon do from a martial arts expert in this free ...', 'English', 66668, 'Tutorial', 'http://i.ytimg.com/vi/oZCOHHSO0UM/mqdefault.jpg', 'taekwondo, flying two direction kick, punch'),
(138, 'AWESOME TAEKWONDO KICKS BY 6 YEAR OLD JEREMY', 'http://www.youtube.com/watch?v=pca_jmtaY1Y', 3, '720', 'This is my 6 year old son Jeremy having fun and practicing his Taekwondo kicks. I created this video with the YouTube Video ...', 'English', 53612, 'Entertainment', 'http://i.ytimg.com/vi_webp/pca_jmtaY1Y/mqdefault.webp', 'taekwondo, kick'),
(139, 'Taekwondo', 'http://www.youtube.com/watch?v=PqYCNSH-Wjo', 2, '360', 'A Taekwondo Video.', 'English', 4127888, 'Others', 'http://i.ytimg.com/vi/PqYCNSH-Wjo/mqdefault.jpg', 'taekwondo'),
(140, 'Taekwondo 540 kick', 'http://www.youtube.com/watch?v=pSyAe0hzkpc', 1, '480', '', 'English', 5673607, 'Entertainment', 'http://i.ytimg.com/vi/pSyAe0hzkpc/mqdefault.jpg', 'taekwondo'),
(141, 'Live Taekwondo Kicking on the BOB XL with Portugal', 'http://www.youtube.com/watch?v=punH15A6W6c', 3, '720', 'A live demonstration of kicks on the BOB XL by myself, Carlos Casquinha, Bruno Fidalgo, Samir Mehmeti and Tiago Graca.', 'English', 177368, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/punH15A6W6c/mqdefault.webp', 'taekwondo, kick'),
(142, 'Taekwondo avec Ludovic Vo - Goodies#46', 'http://www.youtube.com/watch?v=PyqKTa1IN48', 5, '1080', 'Ludovic Vo fut un de nos plus célèbres compétiteurs de Taekwondo. Durant de nombreuses années, il relève tous les défis, ...', 'Non-English', 142812, 'Group demo', 'http://i.ytimg.com/vi_webp/PyqKTa1IN48/mqdefault.webp', 'taekwondo'),
(143, 'Taekwondo: Revolution of kicking vol.1/2 in inglis', 'http://www.youtube.com/watch?v=Q0iPZa-s8xg', 111, '240', 'taekwondo kick´s tutorial. english version.', 'English', 684339, 'Tutorial', 'http://i.ytimg.com/vi_webp/Q0iPZa-s8xg/mqdefault.webp', 'taekwondo'),
(144, 'Exhibición del equipo Nacional Coreano de Tae Kwon', 'http://www.youtube.com/watch?v=Q5sgpyZ1gGY', 4, '240', '', 'Non-English', 440299, 'Group demo', 'http://i.ytimg.com/vi_webp/Q5sgpyZ1gGY/mqdefault.webp', 'taekwondo'),
(145, 'This is TAEKWONDO (Best of)', 'http://www.youtube.com/watch?v=QeNGB8R78Zw', 4, '480', 'Taekwondo (auch Tae-Kwon-Do oder Taekwon-Do) ist ein koreanischer Kampfsport. Die drei Silben des Namens stehen für ', 'English', 96965, 'Entertainment', 'http://i.ytimg.com/vi_webp/QeNGB8R78Zw/mqdefault.webp', 'taekwondo'),
(146, 'taekwondo music video: way of life', 'http://www.youtube.com/watch?v=QHS89bCMUjQ', 5, '240', '540kick.com } what is taekwondo?', 'English', 82186, 'Entertainment', 'http://i.ytimg.com/vi/QHS89bCMUjQ/mqdefault.jpg', 'taekwondo'),
(147, 'Taekwondo Jumping Back Kick Tutorial (taekwonwoo)', 'http://www.youtube.com/watch?v=Qlbe6KjaAgA', 2, '720', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 86681, 'Tutorial', 'http://i.ytimg.com/vi/Qlbe6KjaAgA/mqdefault.jpg', 'taekwondo, back kick, jump back kick'),
(148, 'PRESENTACION DEL PROGRAMA MUNDIAL DE ENTRENAMIENTO', 'http://www.youtube.com/watch?v=qY-Efb00KLI', 12, '1080', 'PRESENTING WORLD TAEKWONDO TRAINING PROGRAM!!! more information at www.wtkdpro.com mas información en ...', 'Non-English', 525696, 'Tutorial', 'http://i.ytimg.com/vi_webp/qY-Efb00KLI/mqdefault.webp', 'taekwondo'),
(149, 'Taekwondo Back Kick vs Round House Kick Counter (t', 'http://www.youtube.com/watch?v=r-a-Y-qSxQ4', 2, '720', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 52780, 'Tutorial', 'http://i.ytimg.com/vi/r-a-Y-qSxQ4/mqdefault.jpg', 'taekwondo, back kick, round house kick'),
(150, 'Taekwondo Turning Kick/Round Kick Tutorial', 'http://www.youtube.com/watch?v=r1O2aMq0akU', 9, '720', '"How to Turning Kick or Round Kick Tutorial" Taekwondo Kickboxing "Turning Kick" (Dollyo Chagi) tutorial broken down and ... HD', 'English', 76128, 'Tutorial', 'http://i.ytimg.com/vi/r1O2aMq0akU/mqdefault.jpg', 'taekwondo, turning kick, round kick'),
(151, 'Master Moon''s Tae Kwon Do - Kids Class', 'http://www.youtube.com/watch?v=rBJTSu-AQLI', 3, '720', 'Master Moon''s World Class Tae Kwon Do is the leading provider of martial arts classes in Eden Prairie. Our children''s class ...', 'English', 68619, 'Tutorial', 'http://i.ytimg.com/vi_webp/rBJTSu-AQLI/mqdefault.webp', 'taekwondo'),
(152, 'Incredible Ultimate N Korean Taekwondo', 'http://www.youtube.com/watch?v=rCcQt62vThY', 4, '360', '', 'Non-English', 2174692, 'Entertainment,Application,Group demo', 'http://i.ytimg.com/vi_webp/rCcQt62vThY/mqdefault.webp', 'taekwondo'),
(154, 'Taekwondo Tornado Round Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=rIrWFaDWjw8', 5, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Tornado Kick" (also known as the 360 Roundhouse / Round Kick), ...', 'English', 405805, 'Tutorial', 'http://i.ytimg.com/vi/rIrWFaDWjw8/mqdefault.jpg', 'taekwondo'),
(155, 'How to Do Horse Stance Drills | Taekwondo Training', 'http://www.youtube.com/watch?v=rN-fNl-QTwg', 2, '1080', 'Watch more How to Do Taekwondo videos: ...', 'English', 52006, 'Tutorial', 'http://i.ytimg.com/vi/rN-fNl-QTwg/mqdefault.jpg', 'taekwondo,horse stance drill'),
(156, 'Rohullah Nikpai Taekwondo Best Kicks', 'http://www.youtube.com/watch?v=RRP7QO6iAvs', 4, '1080', 'All Rights Reserved To Their Rightful Owners.', 'Non-English', 252135, 'Entertainment', 'http://i.ytimg.com/vi_webp/RRP7QO6iAvs/mqdefault.webp', 'taekwondo'),
(157, 'Taekwondo VS Street Fighter (Real Fight)', 'http://www.youtube.com/watch?v=rrYXd8NlhCs', 1, '360', 'Check out my website MaCVlad.webs.com', 'English', 34776280, 'Application', 'http://i.ytimg.com/vi_webp/rrYXd8NlhCs/mqdefault.webp', 'taekwondo'),
(158, 'Team-M Taekwondo: 360, 540, 600, 720, & back-flip', 'http://www.youtube.com/watch?v=rwV42s8Q-xI', 2, '1080', 'Team-M Facebook http://www.facebook.com/Mteamtkd Team-M Website http://www.mteam.net Team-M Youtub', 'English', 283659, 'Tutorial', 'http://i.ytimg.com/vi_webp/rwV42s8Q-xI/mqdefault.webp', 'taekwondo'),
(159, 'Taekwondo vol 1', 'http://www.youtube.com/watch?v=RxHcmW9g7pE', 3, '480', '', 'English', 2597624, 'Entertainment', 'http://i.ytimg.com/vi/RxHcmW9g7pE/mqdefault.jpg', 'taekwondo'),
(160, 'Taekwondo Side Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=S62icvCN6kM', 10, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "Side Kick", effective in Kickboxing, MMA & Olympic style competition.', 'English', 155213, 'Tutorial', 'http://i.ytimg.com/vi/S62icvCN6kM/mqdefault.jpg', 'taekwondo, side kick'),
(161, 'One-on-One Tricking Battle - Red Bull Kick It 2014', 'http://www.youtube.com/watch?v=SAjhv35-q80', 2, '1080', 'Red Bull ''Kick It'' 2014 was held at National Theatre in Seoul Korea hosting the top 16 players competing in search to find the ...', 'English', 296137, 'Entertainment', 'http://i.ytimg.com/vi_webp/SAjhv35-q80/mqdefault.webp', 'taekwondo'),
(162, '2011 Taekwondo vs B-Boy Battle', 'http://www.youtube.com/watch?v=SDe5Ezxej9g', 10, '480', 'K-Tigers Taekwondo vs B-Boy Allstar brakers Facebook pages: http://www.facebook.com/#!', 'Non-English', 88420, 'Entertainment', 'http://i.ytimg.com/vi_webp/SDe5Ezxej9g/mqdefault.webp', 'taekwondo');
INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(163, '2004 Athens Taekwondo', 'http://www.youtube.com/watch?v=sfGz35FyV0U', 7, '240', '2004 Athens Taekwondo Highlights', 'English', 2364123, 'Entertainment', 'http://i.ytimg.com/vi/sfGz35FyV0U/mqdefault.jpg', 'taekwondo, 2004 Athens'),
(164, 'How to Improve Your High Kicking Skills in a Week ', 'http://www.youtube.com/watch?v=sjz_Psy7KYA', 3, '1080', 'Subscribe Now: http://www.youtube.com/subscription_center?add_user=Ehows... Watch More: ...', 'English', 76396, 'Tutorial', 'http://i.ytimg.com/vi/sjz_Psy7KYA/mqdefault.jpg', 'taekwondo, high kick'),
(165, 'korean tigers (taekwondo)', 'http://www.youtube.com/watch?v=SOf6U6Q5Mro', 2, '480', 'wanna play some more?', 'Non-English', 1900535, 'Group demo', 'http://i.ytimg.com/vi/SOf6U6Q5Mro/mqdefault.jpg', 'taekwondo'),
(166, 'Taekwondo vs Muay Thai (Crazy KO)', 'http://www.youtube.com/watch?v=sPNoGhdhKyw', 2, '240', 'Taekwondo vs Muay Thai one dude got knock out bad..', 'English', 3789776, 'Entertainment,Application', 'http://i.ytimg.com/vi_webp/sPNoGhdhKyw/mqdefault.webp', 'taekwondo'),
(167, 'TaeKwonDo, 360°, 540° et 720° Kick', 'http://www.youtube.com/watch?v=T9Ip0pYj_Zo', 3, '720', '', 'English', 92333, 'Tutorial', 'http://i.ytimg.com/vi_webp/T9Ip0pYj_Zo/mqdefault.webp', 'taekwondo'),
(168, 'Taekwondo técnicas de contraataque [TKD WTF] 1 de ', 'http://www.youtube.com/watch?v=TgdrBtBfaRc', 15, '480', 'un video de taewkondo parte 2.', 'Non-English', 226681, 'Tutorial', 'http://i.ytimg.com/vi_webp/TgdrBtBfaRc/mqdefault.webp', 'taekwondo'),
(169, 'The Film Kicking Style of JCVD performed by Taekwo', 'http://www.youtube.com/watch?v=TOpGZU83W94', 3, '720', 'Van Damme : His film kicking Style demonstrated for real by the Taekwondo Master "Vasilis Alexandris" (8th Degree Black Belt)', 'English', 75036, 'Group demo', 'http://i.ytimg.com/vi_webp/TOpGZU83W94/mqdefault.webp', 'taekwondo'),
(170, 'taekwondo 540 kick', 'http://www.youtube.com/watch?v=tt3NB_VtBfU', 1, '240', '540kick.com } taekwondo korea national demonstraion team member 540 kick. best 540 kick i''ve ever seen. TIA missionary ...', 'English', 3498565, 'Group demo', 'http://i.ytimg.com/vi/tt3NB_VtBfU/mqdefault.jpg', 'taekwondo'),
(171, 'Taekwondo:combat tutorial vol.1 "Basic skills"', 'http://www.youtube.com/watch?v=TUnZkMTsGmU', 125, '480', 'Taekwondo combat tutorial subtitulated in english.', 'Non-English', 145452, 'Tutorial', 'http://i.ytimg.com/vi_webp/TUnZkMTsGmU/mqdefault.webp', 'taekwondo'),
(172, 'taekwondo ko top 20', 'http://www.youtube.com/watch?v=tZcY2Thq3Gg', 8, '480', 'video sport taekwondo and music watsh ...', 'English', 1535001, 'Entertainment', 'http://i.ytimg.com/vi_webp/tZcY2Thq3Gg/mqdefault.webp', 'taekwondo'),
(173, 'Very rare fight kung fu vs taekwondo (Master Ehsan', 'http://www.youtube.com/watch?v=u0CIy9ZZEQE', 1, '480', 'Ehsan Shafiq is an afghan champion,In 1994 Ehsan faced a black belt Taekwondo dangerous fighter,after 9 minutes of fighting, Ehsan finished his fight by knock out.Ehsan Has 7 Kung Fu School bassed in london. Contact Ehsan On 07961929695', 'Non-English', 10888158, 'Entertainment,Application', 'http://i.ytimg.com/vi/u0CIy9ZZEQE/mqdefault.jpg', 'taekwondo'),
(174, 'Roundhouse Kick Karate VS Muay Thai Roundhouse, Ho', 'http://www.youtube.com/watch?v=uf7oO1uY8mw', 12, '480', 'Roundhouse Muay Thai Vs Round Karate A Hybrid Roundhouse Kick More Videos @ http://www.elasticsteel.net/Articles.asp? CC', 'English', 222069, 'Tutorial', 'http://i.ytimg.com/vi/uf7oO1uY8mw/mqdefault.jpg', 'taekwondo'),
(175, 'taekwondo 540 720 kick', 'http://www.youtube.com/watch?v=UlSUUAw5beg', 1, '240', '540kick.com } another cool 540 n 720 kicks by dongkwon kang in Korea.', 'Non-English', 715157, 'Group demo', 'http://i.ytimg.com/vi/UlSUUAw5beg/mqdefault.jpg', 'taekwondo, kick'),
(176, 'Taekwondo Chelyabinsk Russia Open 2013 Korean Tige', 'http://www.youtube.com/watch?v=UVJCZ8LM9I8', 19, '720', '', 'Non-English', 134811, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/UVJCZ8LM9I8/mqdefault.webp', 'taekwondo'),
(177, 'Taekwondo: Advanced Hook Kick Counter (taekwonwoo)', 'http://www.youtube.com/watch?v=UxpSBRcKKsg', 2, '720', 'Visit our website: http://www.taekwonwoo.net or visit our school (Woo''s Yong-In Martial Arts) at 133 Indian Trail Road North, Indian ...', 'English', 71825, 'Tutorial', 'http://i.ytimg.com/vi/UxpSBRcKKsg/mqdefault.jpg', 'taekwondo'),
(178, 'Unbelievable Taekwondo kid!!', 'http://www.youtube.com/watch?v=uZ_7Pwi6LnU', 7, '360', 'Frederik Emil Olsen - Denmark - 7 years old!!!', 'Non-English', 176545, 'Entertainment', 'http://i.ytimg.com/vi_webp/uZ_7Pwi6LnU/mqdefault.webp', 'taekwondo'),
(179, 'Taekwondo Kicking and Training Sampler on the BOB ', 'http://www.youtube.com/watch?v=V9aWdHIjMxw', 2, '720', 'Me doing some Taekwondo kicks and punches on a B.O.B (270lbs Dummy). Most of the moves are for fun and demonstration purposes, I wouldn''t actually do them in a competition or fight and they are also mostly sport variation kicks for light to semi contact sparring. Please Like, Comment and Subscribe. I hope you like it ', 'English', 1014326, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/V9aWdHIjMxw/mqdefault.jpg', 'taekwondo'),
(180, 'Taekwondo Spiderman | Flips & Kicks', 'http://www.youtube.com/watch?v=VF_H2oOFn10', 3, '720', 'Spiderman Training Flips, Kicks, punches and Crazy Attacks. Also, some on the BOB (Body Opponent Bag).', 'English', 6149483, 'Entertainment,Application', 'http://i.ytimg.com/vi/VF_H2oOFn10/mqdefault.jpg', 'taekwondo'),
(181, 'Taekwondo Reverse Hook Kick Demo. (taekwonwoo) 태권도', 'http://www.youtube.com/watch?v=vhpHQdaIF0I', 1, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'Non-English', 131831, 'Tutorial', 'http://i.ytimg.com/vi/vhpHQdaIF0I/mqdefault.jpg', 'taekwondo, reverse hook kick'),
(182, 'SPIDER-GIRL - Taekwondo | Kickboxing', 'http://www.youtube.com/watch?v=VM6S5-GSmnI', 5, '1080', 'You can visit us online at: https://www.facebook.com/pages/Pecoraros-Fitness-Kickboxi... ...', 'English', 256414, 'Entertainment', 'http://i.ytimg.com/vi_webp/VM6S5-GSmnI/mqdefault.webp', 'taekwondo'),
(183, 'Taekwondo WTF SOUTH KOREA.. best kicking !', 'http://www.youtube.com/watch?v=VQu4yQxYwJE', 4, '240', 'Taekwondo WTF (world taekwondo federation, is a south korean martial art and full contact fight sport)... best kicking SOUTH ...', 'Non-English', 189556, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/VQu4yQxYwJE/mqdefault.webp', 'taekwondo'),
(184, 'TAEKWONDO LITTLE KID DENMARK FREDERIK EMIL OLSEN', 'http://www.youtube.com/watch?v=VWFLbZVhQzY', 12, '240', '', 'Non-English', 112578, 'Tutorial', 'http://i.ytimg.com/vi_webp/VWFLbZVhQzY/mqdefault.webp', 'taekwondo'),
(185, 'niño de 5 años, pelea de taekwondo. parte 1', 'http://www.youtube.com/watch?v=wCXbGQrEtoM', 2, '720', '', 'Non-English', 85502, 'Entertainment', 'http://i.ytimg.com/vi_webp/wCXbGQrEtoM/mqdefault.webp', 'taekwondo'),
(186, 'Seidokaikan karate VS Taekwondo', 'http://www.youtube.com/watch?v=wgb0yJe2v4s', 1, '240', 'This is Seidokaikan Karate World Cup in 1993, the bout was between EX-Seidokaikan fighter Satake and Taekwondo Fighter ...', 'Non-English', 2538258, 'Entertainment', 'http://i.ytimg.com/vi/wgb0yJe2v4s/mqdefault.jpg', 'taekwondo, fight'),
(187, 'Mirme Taekwondo _Mincheol Shin''Taekwondo kick''', 'http://www.youtube.com/watch?v=WKd7vH1mq-0', 2, '1080', 'Mirme Taekwondo demo kick various(target) http://www.facebook.com/mirmetkd http://www.youtube.com/mirmekoreatkd.', 'Non-English', 67795, 'Tutorial', 'http://i.ytimg.com/vi/WKd7vH1mq-0/mqdefault.jpg', 'taekwondo, kick'),
(188, 'Taekwondo: What you must know in Taekwondo sparrin', 'http://www.youtube.com/watch?v=wl83JxiOQRA', 4, '720', 'What''s your TKD training challenge? Let http://www.taekwonwoo.net find the most effective and affordable online taekwondo ... HD', 'English', 51098, 'Tutorial', 'http://i.ytimg.com/vi/wl83JxiOQRA/mqdefault.jpg', 'taekwondo'),
(189, 'Taekwondo 540 kick tutorial (taekwonwoo) 540도 뒤후려차', 'http://www.youtube.com/watch?v=WLysnY57J-o', 4, '720', 'Online taekwondo training with Master Woo ▻ http://taekwonwoo.net/online_taekwondo_training.php Yong-In Martial Arts, aka ...', 'Non-English', 143256, 'Tutorial', 'http://i.ytimg.com/vi/WLysnY57J-o/mqdefault.jpg', 'taekwondo, 540 kick'),
(190, 'KH Kim''s Taekwondo Taegeuk 1-8', 'http://www.youtube.com/watch?v=WP9DbhRjs8Y', 10, '480', 'Taegeuk 1-8, Master Karloff, Master Alfred Paloma, produced and directed by Oskar Friedl.', 'English', 327856, 'Tutorial', 'http://i.ytimg.com/vi_webp/WP9DbhRjs8Y/mqdefault.webp', 'taekwondo'),
(191, 'Taekwondo - Techniques de coups de pieds', 'http://www.youtube.com/watch?v=wSEuYuORUjQ', 53, '480', 'Taekwondo - Techniques supérieures de haute compétition - Cours COMPLET Taekwondo, art martial et discipline Olympique', 'Non-English', 175996, 'Group demo', 'http://i.ytimg.com/vi_webp/wSEuYuORUjQ/mqdefault.webp', 'taekwondo'),
(192, 'taekwondo best fights', 'http://www.youtube.com/watch?v=x4u5RKF9Trs', 15, '360', 'videos created by claudiotex and edited for leonardoariasabogado....for Taekwondo lovers.', 'English', 203856, 'Entertainment', 'http://i.ytimg.com/vi_webp/x4u5RKF9Trs/mqdefault.webp', 'taekwondo, Olympic'),
(193, 'Taekwondo Side Kick Tutorial', 'http://www.youtube.com/watch?v=X7A96CgJ4GQ', 11, '720', '"How to Side Kick Tutorial" Taekwondo Kickboxing "Side Kick" (Yop Chagi) tutorial broken down and explained by me (Aaron ...', 'English', 211025, 'Tutorial', 'http://i.ytimg.com/vi/X7A96CgJ4GQ/mqdefault.jpg', 'taekwondo, side kick'),
(194, 'Taekwondo Triple Round Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=XLs9Npll9Zo', 8, '1080', 'This is a detailed Taekwondo Kickboxing tutorial for the "Triple Roundhouse Kick" (a.k.a. alternating jumping round kick), effective ...', 'English', 51365, 'Group demo', 'http://i.ytimg.com/vi/XLs9Npll9Zo/mqdefault.jpg', 'taekwondo'),
(195, '3. Taekwondo Poomsae Taegeuk Sam Jang (WTF)', 'http://www.youtube.com/watch?v=XMhY2Ioeof8', 1, '240', 'This poomsae represents Fire. Related to this symbol is also East and the relationship of the Second Daughter. Fire contains a lot ...', 'Non-English', 424919, 'Tutorial', 'http://i.ytimg.com/vi/XMhY2Ioeof8/mqdefault.jpg', 'taekwondo'),
(196, 'Shaolin Monk vs Taekwondo Master (HQ)', 'http://www.youtube.com/watch?v=xqM75eGR98k', 4, '360', 'Taekwondo(Korea) vs Kung fu(Shaolin,China)', 'Non-English', 4421696, 'Entertainment,Application', 'http://i.ytimg.com/vi_webp/xqM75eGR98k/mqdefault.webp', 'taekwondo, shaolin'),
(197, 'Taekwondo Drills Training', 'http://www.youtube.com/watch?v=xyQOvkKBlmU', 6, '240', 'Taekwondo Drills. www.nongjangbelgium.be.', 'English', 455849, 'Tutorial', 'http://i.ytimg.com/vi/xyQOvkKBlmU/mqdefault.jpg', 'taekwondo'),
(198, 'Olympic Taekwondo Training', 'http://www.youtube.com/watch?v=Y7sxAV2IaNs', 3, '480', 'Olympic Taekwondo Training with Master Rim.', 'English', 132956, 'Tutorial', 'http://i.ytimg.com/vi/Y7sxAV2IaNs/mqdefault.jpg', 'taekwondo, olympic'),
(199, 'Master Park - Coups de pied de base du Taekwondo', 'http://www.youtube.com/watch?v=Y8i7zro9UD8', 4, '360', 'Taekwondo Cassette de Maitre Park Moon Soo http://www.the-savoisien.com Ap Tchagui Yop Tchagui Tolyo Tchagui Bandal ...', 'Non-English', 111548, 'Tutorial', 'http://i.ytimg.com/vi_webp/Y8i7zro9UD8/mqdefault.webp', 'taekwondo'),
(200, 'TAEKWONDO ANDRE LIMA (9 Million Views)', 'http://www.youtube.com/watch?v=yhAM7aaJ4xM', 2, '480', 'HONORS (1st WEEK)', 'English', 9337372, 'Entertainment,Others', 'http://i.ytimg.com/vi/yhAM7aaJ4xM/mqdefault.jpg', 'taekwondo'),
(201, 'Taekwondo Round Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=yIawbHsotgI', 8, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the basic "Round Kick" (not to be confused with the circular version of the ...', 'English', 1777166, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi_webp/yIawbHsotgI/mqdefault.webp', 'taekwondo, round kick'),
(202, 'Taekwondo display by the Korean army at the 2013 H', 'http://www.youtube.com/watch?v=YOztk-EidhE', 17, '720', 'Visit Taekwondo News on Facebook at\r\nhttps://www.facebook.com/pages/Taekwo...', 'Non-English', 745824, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/YOztk-EidhE/mqdefault.webp', 'taekwondo'),
(203, 'The Best Taekwondo Moves Slow Motion!', 'http://www.youtube.com/watch?v=yqx3_x6OcdI', 3, '480', 'Taekwodo, KArati, kick boxing, Kukkiwon, demonstartion, korea, japan, china, Shoalin are all good martial arts to me...', 'Non-English', 289375, 'Entertainment', 'http://i.ytimg.com/vi_webp/yqx3_x6OcdI/mqdefault.webp', 'taekwondo'),
(204, 'Taekwondo 360 Back Kick Tutorial (Kwonkicker)', 'http://www.youtube.com/watch?v=Yxqe8hVgpoY', 4, '480', 'This is a detailed Taekwondo Kickboxing tutorial for the "360 Back Kick", effective in Kickboxing, MMA & Olympic style competition.', 'English', 178179, 'Tutorial', 'http://i.ytimg.com/vi/Yxqe8hVgpoY/mqdefault.jpg', 'taekwondo, back kick'),
(205, 'Taekwondo Combo Kicks, Turning Kicks, Single Kicks', 'http://www.youtube.com/watch?v=Z7AJ5seXpVU', 7, '1080', '** please check out the " 2013 new series " at ', 'English', 1268558, 'Tutorial', 'http://i.ytimg.com/vi_webp/Z7AJ5seXpVU/mqdefault.webp', 'taekwondo'),
(206, 'Won- Hyo Tul Taekwon-do Estilo ITF', 'http://www.youtube.com/watch?v=ZaJfiBHIWqU', 3, '360', 'First of all this kick is not for fighting, it is a flashy move and to show your that you can do more advanced kicks. So NO haters ...', 'English', 62527, 'Tutorial', 'http://i.ytimg.com/vi_webp/ZaJfiBHIWqU/mqdefault.webp', 'taekwondo'),
(207, 'Ultimate Martial Arts Fails Compilation 2013 || Un', 'http://www.youtube.com/watch?v=ZcOFPgB-Mf4', 4, '720', 'Ultimate Martial Arts Fails Compilation 2013 || Uniformedia Make sure you are watching this video in HD! "COPYRIGHT ...', 'English', 2939121, 'Entertainment', 'http://i.ytimg.com/vi/ZcOFPgB-Mf4/mqdefault.jpg', 'taekwondo'),
(208, 'Taekwondo Lower Body Strength Drills (Kwonkicker)', 'http://www.youtube.com/watch?v=zisnttKPGNw', 14, '480', 'This is a detailed Taekwondo Kickboxing tutorial for basic lower body strength and agility training drills & exercises. These drills ...', 'English', 187268, 'Tutorial', 'http://i.ytimg.com/vi/zisnttKPGNw/mqdefault.jpg', 'taekwondo'),
(209, 'Taekwondo vs Muay Thai 2014', 'http://www.youtube.com/watch?v=zjZbQ5QqCHU', 5, '1080', 'A Taekwondo fighter (Kwonkicker) goes up against a Muay Thai fighter (Shane Fazen) in this martial arts fight scene, produced by Fight Tips.', 'English', 2473322, 'Entertainment', 'http://i.ytimg.com/vi/zjZbQ5QqCHU/mqdefault.jpg', 'taekwondo'),
(210, 'Taekwondo training in Korea', 'http://www.youtube.com/watch?v=ZKhCJ1nMwJg', 3, '240', 'Kyung Hee University Taekwondo fighters training.', 'Non-English', 208935, 'Others', 'http://i.ytimg.com/vi/ZKhCJ1nMwJg/mqdefault.jpg', 'taekwondo'),
(211, 'Taekwondo Poomse 4', 'http://www.youtube.com/watch?v=Zl6amJnkbV4', 3, '360', '', 'English', 53239, 'Others', 'http://i.ytimg.com/vi_webp/Zl6amJnkbV4/mqdefault.webp', 'taekwondo'),
(212, 'TAEKWONDO WTF bag training', 'http://www.youtube.com/watch?v=zMflpRe_Rmo', 2, '360', 'packed full of Taekwondo WTF techniques.', 'English', 688693, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi_webp/zMflpRe_Rmo/mqdefault.webp', 'taekwondo'),
(213, 'taekwondo beijing 2008', 'http://www.youtube.com/watch?v=zOp_OK5-aUY', 4, '360', 'Este es un video de taekwondo que vi en internet, taekwondo en beijing 2008 me gusto muxo por eso kiero compartirlo con ...', 'Non-English', 123824, 'Entertainment', 'http://i.ytimg.com/vi_webp/zOp_OK5-aUY/mqdefault.webp', 'taekwondo,Olympic'),
(214, 'campeon mundial de taekwondo', 'http://www.youtube.com/watch?v=zuXWl9S0__U', 3, '240', 'segundo tributo a bren foster muy buen video.', 'Non-English', 687465, 'Entertainment', 'http://i.ytimg.com/vi/zuXWl9S0__U/mqdefault.jpg', 'taekwondo'),
(215, 'The Best Taekwondo Fight EVER!!!! The Cutest Thing', 'http://www.youtube.com/watch?v=ZWYzUaiBqzs', 5, '1080', 'This video proves how we can be winners without necessarily fighting. To promote Taekwondo using and comparing students ...', 'English', 666131, 'Entertainment', 'http://i.ytimg.com/vi_webp/ZWYzUaiBqzs/mqdefault.webp', 'taekwondo'),
(216, '720 kick in a real Taekwondo fight!', 'http://www.youtube.com/watch?v=zymfvBOESio', 1, '480', 'A awesome Taekwondo kick from the TV-show, The human weapon.', 'English', 200404, 'Entertainment', 'http://i.ytimg.com/vi/zymfvBOESio/mqdefault.jpg', 'taekwondo');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fun_video`
--
ALTER TABLE `fun_video`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fun_video`
--
ALTER TABLE `fun_video`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=217;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
